# Generated by Django 2.0.9 on 2018-11-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trench', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mfamethod',
            old_name='name',
            new_name='method',
        ),
        migrations.AlterField(
            model_name='mfamethod',
            name='method',
            field=models.CharField(choices=[('app', 'Application'), ('email', 'E-mail'), ('sms', 'SMS'), ('yubi', 'YubiKey')], default='test', max_length=255, verbose_name='method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mfamethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
