from django.utils.translation import gettext_lazy as _

from trench.providers.base import AbstractMessageDispatcher


class YubiKeyBackend(AbstractMessageDispatcher):

    def dispatch_message(self):
        """
        Do nothing. Code must be generated by YubiKey.
        """

        return {
            'message': _('Generate code using your YubiKey')
        }
